const defaultSubmission = {
  consented: true,
  consented_at: new Date(),
  printed_name: "",
  files: [],
  gender: "",
  is_hispanic_or_latino: "",
  race: "",
  age: "",
  partner: "",
  dependents: "",
  income: "",
  accepted: "",
  security_deposit: "",
  rent: "",
  bedrooms: "",
  house_type: "",
  voucher: "",
  minimum_rent: "",
  landlord_name: "",
  property_address: "",
  property_address_city: "",
  property_address_state: "",
  property_address_zipcode: "",
  experience_freeform: "",
  interview_possible: "",
  email: "",
  email_confirm: ""
}

export default defaultSubmission;