const defaultSubmission = {
  consented: false,
  consented_at: "",
  printed_name: "Wonyoung So",
  files: [],
  gender: "man",
  transgender: "yes",
  is_hispanic_or_latino: "no",
  race: "asian",
  age: "30-39",
  partner: "yes",
  dependents: "1",
  income: "3500",
  accepted: "accepted",
  security_deposit: "2500",
  rent: "2500",
  bedrooms: "1",
  house_type: "multifamily",
  voucher: "yes",
  minimum_rent: "25",
  landlord_name: "VIVA",
  landlord_scale: "individual",
  property_address: "45",
  property_address_city: "Cambridge",
  property_address_state: "Massachusetts",
  property_address_zipcode: "02142",
  experience_freeform: "dfije",
  interview_possible: "yes",
  email: "wonyoung.so.work@gmail.com",
  email_confirm: "wonyoung.so.work@gmail.com",
  report_date_month: "June",
  report_date_year: "2020",
  rent_apply_date_month: null,
  rent_apply_date_year: null
}

export default defaultSubmission;

// printed_name: "Wonyoung So",
// files: [],
// gender: "male",
// is_hispanic_or_latino: "no",
// race: "asian",
// age: "30-39",
// partner: "yes",
// dependents: "1",
// income: "3500",
// accepted: "accepted",
// security_deposit: "2500",
// rent: "2500",
// bedrooms: "1",
// house_type: "multifamily",
// voucher: "yes",
// minimum_rent: "25",
// landlord_name: "VIVA",
// property_address: "45",
// property_address_city: "Cambridge",
// property_address_state: "Massachusetts",
// property_address_zipcode: "02142",
// experience_freeform: "dfije",
// interview_possible: "yes",
// email: "wonyoung.so.work@gmail.com",
// email_confirm: "wonyoung.so.work@gmail.com"